### ISSUE TITLE
typing dependency causes errors on Python 3.8

### ISSUE THREAD

**Issue by stuartc** [BusinessOptics/fn_graph#4]
`typing` comes with 3.8 (and earlier ones as well?). I'm getting errors like this when trying to install things.

```
    File "/usr/local/lib/python3.8/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/usr/local/lib/python3.8/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
```

`typing` shouldn't be coming from `site-packages`. Is it a necessary dependency in general? And if so, are we able to conditionally include it if the installer already has 3.8?

**Comment by alexmojaki** [comment]
https://community.plone.org/t/solved-attributeerror-type-object-callable-has-no-attribute-abc-registry/11514

https://pypi.org/project/typing/

Looks like the package should only be needed in older Pythons, remove the dependency.
