### ISSUE TITLE
Wrapping functions after definition

### ISSUE THREAD

**Issue by omyllymaki** [BusinessOptics/fn_graph#7]
Is there a simple way to wrap functions after definition and then pass to a composer? I tried to change function name to the original one after wrapping, but it gives TypeError about function arguments after that. Here is a minimal example where I tried to wrap functions to add timing to every function:

```
import time

from fn_graph.fn_graph import Composer


def timer(func):
    def inner(*args, **kwargs):
        print(args, kwargs)
        t1 = time.time()
        out = func(*args, **kwargs)
        t2 = time.time()
        print(f"Function {func} took {1000 * (t2 - t1)} ms")
        return out
    
    # Change the name of wrapped function to original one
    inner.__name__ = func.__name__
    return inner


def a():
    return 5


def b(a):
    return a + 3


def c(b):
    return b * 2


functions = [a, b, c]
functions = [timer(f) for f in functions]
composer = Composer().update(*functions)

result = composer.calculate("c")

```
The error it gives is:
TypeError: c() missing 1 required positional argument: 'b'

**Comment by alexmojaki** [comment]
Decorate `inner` with `@functools.wraps(func)`. This takes care of `__name__` as well as letting `inspect.signature` know to look at `func` for the real signature of `inner`, so fn_graph knows what arguments it needs to pass to `c`.

**Comment by omyllymaki** [comment]
Perfect, it works. Thank you very much!
